//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/rishiyaduwanshi/boiler/internal/cli"
	"github.com/spf13/cobra/doc"
)

var markdownListPrefixRe = regexp.MustCompile(`^([-*+]\s+|\d+\.\s+)`)
var markdownPlaceholderTokenRe = regexp.MustCompile(`\[[A-Za-z0-9_./|=-]+\]`)
var markdownAnglePlaceholderRe = regexp.MustCompile(`<[A-Za-z][A-Za-z0-9_-]*>`)
var markdownPlainURLRe = regexp.MustCompile(`https?://[^\s)]+`)

func main() {
	rootCmd := cli.GetRootCommand()

	// Generate to web directory
	docsDir := "./web/src/content/docs/commands"

	// Clean existing files
	if err := os.RemoveAll(docsDir); err != nil {
		log.Fatalf("Failed to clean docs directory: %v", err)
	}

	// Create directory
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		log.Fatalf("Failed to create docs directory: %v", err)
	}

	// Generate markdown docs
	if err := doc.GenMarkdownTree(rootCmd, docsDir); err != nil {
		log.Fatal(err)
	}

	// Post-process: add frontmatter and cleanup
	if err := processMarkdownFiles(docsDir); err != nil {
		log.Fatal(err)
	}

	log.Println("✓ Command reference docs generated in", docsDir)
}

func processMarkdownFiles(dir string) error {
	files, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return err
	}

	for _, file := range files {
		if err := processFile(file); err != nil {
			return fmt.Errorf("error processing %s: %w", file, err)
		}
	}

	return nil
}

func processFile(filePath string) error {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}

	lines := strings.Split(string(content), "\n")
	if len(lines) == 0 {
		return nil
	}

	// Extract title from first heading
	title := strings.TrimPrefix(lines[0], "## ")

	// Remove SEE ALSO section
	cleanContent := regexp.MustCompile(`(?s)### SEE ALSO\n\n.*?\n\n###### Auto generated by.*?\n`).
		ReplaceAllString(string(content), "")

	// Remove first heading (title is in frontmatter)
	cleanContent = strings.TrimPrefix(cleanContent, lines[0]+"\n\n")
	cleanContent = sanitizeMarkdownIndent(cleanContent)

	// Add Starlight frontmatter
	finalContent := fmt.Sprintf(`---
title: %s
description: Command reference for %s
---

%s`, title, title, cleanContent)

	return os.WriteFile(filePath, []byte(finalContent), 0644)
}

func sanitizeMarkdownIndent(content string) string {
	lines := strings.Split(content, "\n")
	inCodeFence := false
	inSectionList := false

	for i, line := range lines {
		normalized := strings.ReplaceAll(line, "\t", "  ")
		normalized = strings.TrimRight(normalized, " ")
		trimmedLine := strings.TrimSpace(normalized)

		if strings.HasPrefix(trimmedLine, "```") {
			lines[i] = trimmedLine
			inCodeFence = !inCodeFence
			inSectionList = false
			continue
		}

		if inCodeFence {
			lines[i] = normalized
			continue
		}

		if trimmedLine == "" {
			lines[i] = ""
			inSectionList = false
			continue
		}

		if strings.HasSuffix(trimmedLine, ":") && !markdownListPrefixRe.MatchString(trimmedLine) {
			lines[i] = sanitizeMarkdownLineTokens(trimmedLine)
			inSectionList = true
			continue
		}

		leadingSpaces := len(normalized) - len(strings.TrimLeft(normalized, " "))
		if inSectionList && leadingSpaces >= 2 {
			if markdownListPrefixRe.MatchString(trimmedLine) {
				lines[i] = sanitizeMarkdownLineTokens(trimmedLine)
			} else {
				lines[i] = "- " + sanitizeMarkdownLineTokens(trimmedLine)
			}
			continue
		}

		if leadingSpaces > 0 {
			normalized = "  " + strings.TrimLeft(normalized, " ")
		}

		lines[i] = sanitizeMarkdownLineTokens(normalized)
		inSectionList = false
	}

	return strings.Join(lines, "\n")
}

func sanitizeMarkdownLineTokens(line string) string {
	if strings.Contains(line, "http://") || strings.Contains(line, "https://") {
		line = markdownPlainURLRe.ReplaceAllStringFunc(line, func(url string) string {
			if strings.HasPrefix(url, "`") && strings.HasSuffix(url, "`") {
				return url
			}
			return "`" + url + "`"
		})
	}

	if strings.Contains(line, "<") && strings.Contains(line, ">") {
		line = markdownAnglePlaceholderRe.ReplaceAllStringFunc(line, func(token string) string {
			return "`" + token + "`"
		})
	}

	if strings.Contains(line, "[") && strings.Contains(line, "]") && !strings.Contains(line, "](") {
		line = markdownPlaceholderTokenRe.ReplaceAllStringFunc(line, func(token string) string {
			return "`" + token + "`"
		})
	}

	return line
}
