//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/rishiyaduwanshi/boiler/internal/cli"
	"github.com/spf13/cobra/doc"
)

func main() {
	rootCmd := cli.GetRootCommand()

	// Generate to web directory
	docsDir := "./web/src/content/docs/commands"

	// Clean existing files
	if err := os.RemoveAll(docsDir); err != nil {
		log.Fatalf("Failed to clean docs directory: %v", err)
	}

	// Create directory
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		log.Fatalf("Failed to create docs directory: %v", err)
	}

	// Generate markdown docs
	if err := doc.GenMarkdownTree(rootCmd, docsDir); err != nil {
		log.Fatal(err)
	}

	// Post-process: add frontmatter and cleanup
	if err := processMarkdownFiles(docsDir); err != nil {
		log.Fatal(err)
	}

	log.Println("✓ Command reference docs generated in", docsDir)
}

func processMarkdownFiles(dir string) error {
	files, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return err
	}

	for _, file := range files {
		if err := processFile(file); err != nil {
			return fmt.Errorf("error processing %s: %w", file, err)
		}
	}

	return nil
}

func processFile(filePath string) error {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}

	lines := strings.Split(string(content), "\n")
	if len(lines) == 0 {
		return nil
	}

	// Extract title from first heading
	title := strings.TrimPrefix(lines[0], "## ")
	
	// Remove SEE ALSO section
	cleanContent := regexp.MustCompile(`(?s)### SEE ALSO\n\n.*?\n\n###### Auto generated by.*?\n`).
		ReplaceAllString(string(content), "")

	// Remove first heading (title is in frontmatter)
	cleanContent = strings.TrimPrefix(cleanContent, lines[0]+"\n\n")

	// Add Starlight frontmatter
	finalContent := fmt.Sprintf(`---
title: %s
description: Command reference for %s
---

%s`, title, title, cleanContent)

	return os.WriteFile(filePath, []byte(finalContent), 0644)
}
